/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
/**
 *
 * @author chris
 */
public class Recuento extends javax.swing.JFrame {
    
    int xMouse, yMouse;

    /**
     * Creates new form Recuento
     */
    public Recuento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        button = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        button24 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        button25 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        exitBtn = new javax.swing.JPanel();
        exitTxt = new javax.swing.JLabel();
        button14 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        button15 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        button16 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        button17 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        button26 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        button27 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        button28 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        button29 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        exitBtn1 = new javax.swing.JPanel();
        exitTxt1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(750, 430));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 430));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        Title.setText("Recuento de votos");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellido", "Voto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 750, 330));

        button.setBackground(new java.awt.Color(18, 90, 173));
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buttonMousePressed(evt);
            }
        });
        button.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file-chart.png"))); // NOI18N
        jLabel1.setText("Gráfico");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });
        button.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button1.setBackground(new java.awt.Color(18, 90, 173));
        button1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button1MousePressed(evt);
            }
        });
        button1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Actualizar");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        button1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button24.setBackground(new java.awt.Color(18, 90, 173));
        button24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button24MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button24MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button24MousePressed(evt);
            }
        });
        button24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Volver");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel25MousePressed(evt);
            }
        });
        button24.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button25.setBackground(new java.awt.Color(18, 90, 173));
        button25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button25MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button25MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button25MousePressed(evt);
            }
        });
        button25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Actualizar");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel26MousePressed(evt);
            }
        });
        button25.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button24.add(button25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button.add(button24, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 140, 30));

        jPanel1.add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 140, 30));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt.setBackground(new java.awt.Color(204, 204, 204));
        exitTxt.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt.setText("X");
        exitTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtnLayout = new javax.swing.GroupLayout(exitBtn);
        exitBtn.setLayout(exitBtnLayout);
        exitBtnLayout.setHorizontalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtnLayout.setVerticalGroup(
            exitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        button14.setBackground(new java.awt.Color(18, 90, 173));
        button14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button14MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button14MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button14MousePressed(evt);
            }
        });
        button14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/book-open-page-variant.png"))); // NOI18N
        jLabel15.setText("Actualizar");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        button14.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 30));

        button15.setBackground(new java.awt.Color(18, 90, 173));
        button15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button15MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button15MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button15MousePressed(evt);
            }
        });
        button15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Actualizar");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });
        button15.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button14.add(button15, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button16.setBackground(new java.awt.Color(18, 90, 173));
        button16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button16MousePressed(evt);
            }
        });
        button16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Actualizar");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel17MousePressed(evt);
            }
        });
        button16.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button17.setBackground(new java.awt.Color(18, 90, 173));
        button17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button17MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button17MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button17MousePressed(evt);
            }
        });
        button17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Actualizar");
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel18MousePressed(evt);
            }
        });
        button17.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button16.add(button17, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button14.add(button16, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        jPanel1.add(button14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 130, 30));

        button26.setBackground(new java.awt.Color(18, 90, 173));
        button26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button26MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button26MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button26MousePressed(evt);
            }
        });
        button26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/home-outline.png"))); // NOI18N
        jLabel27.setText("Volver");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel27MousePressed(evt);
            }
        });
        button26.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button27.setBackground(new java.awt.Color(18, 90, 173));
        button27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button27MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button27MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button27MousePressed(evt);
            }
        });
        button27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Actualizar");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel28MousePressed(evt);
            }
        });
        button27.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button26.add(button27, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button28.setBackground(new java.awt.Color(18, 90, 173));
        button28.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button28MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button28MousePressed(evt);
            }
        });
        button28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Volver");
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel29MousePressed(evt);
            }
        });
        button28.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button29.setBackground(new java.awt.Color(18, 90, 173));
        button29.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        button29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                button29MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                button29MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                button29MousePressed(evt);
            }
        });
        button29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Actualizar");
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel30MousePressed(evt);
            }
        });
        button29.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 100, 30));

        button28.add(button29, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 140, 30));

        button26.add(button28, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 260, 140, 30));

        jPanel1.add(button26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 140, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        exitBtn1.setBackground(new java.awt.Color(255, 255, 255));

        exitTxt1.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        exitTxt1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exitTxt1.setText("X");
        exitTxt1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        exitTxt1.setPreferredSize(new java.awt.Dimension(40, 40));
        exitTxt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitTxt1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitTxt1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitTxt1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout exitBtn1Layout = new javax.swing.GroupLayout(exitBtn1);
        exitBtn1.setLayout(exitBtn1Layout);
        exitBtn1Layout.setHorizontalGroup(
            exitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(exitBtn1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        exitBtn1Layout.setVerticalGroup(
            exitBtn1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitTxt1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(exitBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 788, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(exitBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMousePressed

    }//GEN-LAST:event_buttonMousePressed

    private void buttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseExited

    }//GEN-LAST:event_buttonMouseExited

    private void buttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonMouseEntered

    }//GEN-LAST:event_buttonMouseEntered

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed

    }//GEN-LAST:event_jLabel1MousePressed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
        //nothing
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void exitTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxtMouseClicked

    private void exitTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxtMouseEntered

    private void exitTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxtMouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxtMouseExited

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void button1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseEntered

    private void button1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MouseExited

    private void button1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1MousePressed

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MousePressed

    private void button15MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseEntered

    private void button15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MouseExited

    private void button15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button15MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button15MousePressed

    private void jLabel17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel17MousePressed

    private void jLabel18MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MousePressed

    private void button17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button17MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button17MouseEntered

    private void button17MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button17MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button17MouseExited

    private void button17MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button17MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button17MousePressed

    private void button16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button16MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button16MouseEntered

    private void button16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button16MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button16MouseExited

    private void button16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button16MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button16MousePressed

    private void button14MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button14MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button14MouseEntered

    private void button14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button14MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button14MouseExited

    private void button14MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button14MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button14MousePressed

    private void jLabel25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MousePressed

    private void jLabel26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MousePressed

    private void button25MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button25MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button25MouseEntered

    private void button25MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button25MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button25MouseExited

    private void button25MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button25MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button25MousePressed

    private void button24MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button24MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button24MouseEntered

    private void button24MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button24MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button24MouseExited

    private void button24MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button24MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button24MousePressed

    private void jLabel27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MousePressed

    private void jLabel28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MousePressed

    private void button27MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button27MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button27MouseEntered

    private void button27MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button27MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button27MouseExited

    private void button27MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button27MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button27MousePressed

    private void jLabel29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MousePressed

    private void jLabel30MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MousePressed

    private void button29MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button29MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button29MouseEntered

    private void button29MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button29MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button29MouseExited

    private void button29MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button29MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button29MousePressed

    private void button28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button28MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button28MouseEntered

    private void button28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button28MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button28MouseExited

    private void button28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button28MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button28MousePressed

    private void button26MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button26MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_button26MouseEntered

    private void button26MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button26MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_button26MouseExited

    private void button26MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button26MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_button26MousePressed

    private void exitTxt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitTxt1MouseClicked

    private void exitTxt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseEntered
        exitBtn.setBackground(Color.red);
        exitTxt.setForeground(Color.white);
    }//GEN-LAST:event_exitTxt1MouseEntered

    private void exitTxt1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitTxt1MouseExited
        exitBtn.setBackground(Color.white);
        exitTxt.setForeground(Color.black);
    }//GEN-LAST:event_exitTxt1MouseExited

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_headerMouseDragged

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recuento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recuento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JPanel button;
    private javax.swing.JPanel button1;
    private javax.swing.JPanel button14;
    private javax.swing.JPanel button15;
    private javax.swing.JPanel button16;
    private javax.swing.JPanel button17;
    private javax.swing.JPanel button24;
    private javax.swing.JPanel button25;
    private javax.swing.JPanel button26;
    private javax.swing.JPanel button27;
    private javax.swing.JPanel button28;
    private javax.swing.JPanel button29;
    private javax.swing.JPanel exitBtn;
    private javax.swing.JPanel exitBtn1;
    private javax.swing.JLabel exitTxt;
    private javax.swing.JLabel exitTxt1;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
